<div class="topo-table">
    <a class="btn btn-success" title="Novo"><span class="glyphicon glyphicon-plus"></span></a>
 
    <div class="btn-group" title="Quantidades por Página">
        <button type="button" class="btn btn-default">005</button>
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu pull-right" style="min-width: 75px" role="menu">
            <li class="active"><a href="#">005</a></li>
            <li><a href="#">010</a></li>
            <li><a href="#">025</a></li>
            <li><a href="#">050</a></li>
            <li><a href="#">100</a></li>
        </ul>
    </div>
 
    <form class="form-inline pull-right" role="form">
        <div class="form-group">
            <label class="sr-only" for="localizar">Buscar...</label>
            <input type="search" class="form-control" id="localizar" placeholder="Bucar...">
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
    </form>
</div>
<br/>

<div class="corpo-table">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Nome</th>
                <th>Tel. Principal</th>
                <th>Tel. Qua.</th>
                <th>Data Criação</th>  
                <th>Ação</th>  
            </tr>
        </thead>
        
        <tbody>
            <?php for($ini = 1; $ini<=5;$ini++):?>
            <tr>
                <td><?php echo $ini;?></td>
                <td>Arapiraca - ALagoas, Br</td>
                <td>(82) 96701058</td>
                <td class="text-center">2</td>
                <td><?php echo date("d/m/Y"); ?></td>
                <td>
                        <a class="btn btn-xs btn-info" title="Visualizar" href=""><span class="glyphicon glyphicon-new-window"></span></a>
                        <a class="btn btn-xs btn-warning" title="Editar" href=""><span class="glyphicon glyphicon-edit"></span></a>
                        <a class="btn btn-xs btn-danger" title="Deletar" href=""><span class="glyphicon glyphicon-floppy-remove"></span></a>
                    </td>
              <?php  endfor?>
            </tr>
        </tbody>
    </table>
</div>
